# Generated by Django 3.0.6 on 2020-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
