# Generated by Django 3.0.6 on 2020-05-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_auto_20200517_0619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeRecord',
        ),
    ]
