# Generated by Django 3.0.6 on 2020-05-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_delete_timerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myActivities',
            field=models.ManyToManyField(blank=True, to='ams.Activity'),
        ),
    ]
